// CHANGE THIS TO THE UNIQUE VALUE OF YOUR ETHERNET SHIELD
static uint8_t mac[] = { 0x90, 0xA2, 0xDA, 0x0D, 0x00, 0x8F };

// CHANGE THIS TO MATCH YOUR HOST NETWORK
static uint8_t ip[] = { 192, 168, 1, 177 };

// USED FOR WEB SERVER
#define PREFIX ""
