// DON'T REMOVE THIS LINE!
searchDB = new Array();

// DEFINE NEW SEARCHABLE ITEMS HERE, FOLLOWING THE FORMAT AS BELOW;
// searchDB[nextnumber] = new searchOption("TitleOfResult", "KeywordsWithCommasOrSpaces", "Description", "URLToPageRelativeFromResults");
searchDB[0] = new searchOption("Setting Up The Gear", "test,testing,browser,ie,ie4,ie5,ie6,compatible,compatibility,up-to-date,plug-ins,plugin,shockwave,acrobat,zip,configure,configuration,information", "The Learning Technologies family of sites make full use of JavaScript, Cookies and Style Sheets. In order for you to view these technologies properly, we need to ensure you are running an appropriate version browser. ", "../sections/settingup/browsertest.html");
searchDB[1] = new searchOption("WebCT Area", "WebCT contents page with links to Introduction to WebCT, Bulletin Boardl, Email, Chat Rooms and Student Web Area.", "Section including Introduction to WebCT, Bulletin Board, Email, Chat Rooms and Students Web Area", "../sections/webct/webct.html");
searchDB[2] = new searchOption("Software Issues and Tutorials", "nero,5,ie4,1e5,1e6,downloading,attaching,files,outlook,2000,burning,rom,optical,character,recognition,ocr,scanner,software,help,tutorial,tutorials,print,key,winzip,zip,winrar,winace,8,zip,issues,browser,freeze", "Section including Attaching Files in Outlook 2000, Nero Burning ROM, Optical Character Recognition (OCR) Tutorial, Print Key 2000 Tutorial, WinZip 8.0 Tutorial and Ian's Definitive Guide to... the Mac!", "../sections/softwaretuts/softwaretuts.html");
searchDB[3] = new searchOption("Glossary of Common Terms", "web,site,webct,upload,toggle,script,thread,folder,forum,forward,html,image,map,internal,mail,isp,reight,click,left,roll-over,filter,external,download,double,default,click,chat,room,line,terms,help,stupid,thing,emc,ed-online", "Glossary of keywords with description and examples.", "../sections/glossary/glossary.html");
searchDB[4] = new searchOption("Introduction to WebCT", "webct,first,access,getting,on,bb,bulletin,amateur,beginner,novice,interface,layout", "Welcome to WebCT 3, an online support package for Web-based educational material. These pages are designed to guide you through the initial stages of WebCT Access. ", "../sections/webct/intro/intro00.html");
searchDB[5] = new searchOption("Bulletin Board", "layout,menu,functions,composing,message,important,notice,forums,disappearing,messages,selecting,all,none,individual,compiling,attaching,files", "The WebCT Bulletin Board is an excellent means of communication with your classmates. Whether you use it as a means of help or just to discuss the latest news, the Bulletin Board is for you!", "../sections/webct/bb/bb.html");
searchDB[6] = new searchOption("Email", "email,layout,mail,message,e-mail,internet,menu,functions,composing,forwarding,internal,selecting,all,none,individual,,compiling,attaching,files", "The WebCT Email section includes Email Layout and Menu Functions, Composing an Email Message, Forwarding Internal Emails, Selecting All and Selecting None, Selecting Individual Messages, Compiling Messages and Attaching Files.", "../sections/webct/email/email.html");
searchDB[7] = new searchOption("Chat Rooms", "chat,rooms,line,loyout,features,opening,multiple,lingo,common,words,smiley,happy,face", "A guide to the WebCT Chat Rooms. Includes Using the Chat Rooms, Chat Room Layout and Features, Opening Multiple Chat Rooms and Chat Line Lingo.", "../sections/webct/chat/chat.html");
searchDB[8] = new searchOption("Student Web Area", "basic,guide,getting,started,viewing,other,sites,your,area,my,mine,webct,file,management,restricted,area", "A basc guide to the Student Web Area. Including Gettign Started, Viewing Other Sites, Your Area and WebCT File Management Tools.", "../sections/webct/studwebarea/studwebarea.html");