#!/bin/sh
# /etc/init.d/salvius
#
### BEGIN INIT INFO
# Provides:          salvius
# Required-Start:    $local_fs $network $remote_fs $syslog
# Required-Stop:     $local_fs $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Salvius
# Description:       Open source humanoid robot
### END INIT INFO

# Exit silently if package is not installed
python -c "import salvius"
[ $? ] || exit 0

NAME=salvius
DAEMON=$(python -c "import sys; from salvius import salvius; sys.stdout.write(salvius.__file__)")
DESC="Salvius"
SCRIPTNAME=/etc/init.d/salvius

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$NAME.pid

# Define LSB log_* functions
. /lib/lsb/init-functions

do_start () {
	log_daemon_msg "Starting $DESC" "$NAME"
    salvius
	log_end_msg $?
}

do_stop () {
	log_daemon_msg "Stopping $DESC" "$NAME"
    killall salvius
	log_end_msg $?
}

case "$1" in
  start)
    do_start&
    ;;
  stop)
    do_stop
    ;;
  restart|reload|force-reload)
    do_stop
    sleep 1
    do_start
    ;;
  status)
    status_of_proc "$NAME" "$DAEMON" && exit 0 || exit $?
    ;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|status}" >&2
	exit 3
    ;;
esac

exit 0
